### ISSUE TITLE
Integration with already existing S3 bucket 

### ISSUE THREAD

**Issue by svoychik** [serverless-operations/serverless-apigateway-service-proxy#103]
I'm trying to make API Gateway integration with already existing S3 Bucket?
Is there a way to reference the bucket by just a bucket name (or arn) without describing it as a part of the resources?
like this: 
```
- s3:
      path: "{userid}/{filename}"
      method: put
      action: PutObject
      bucket:
        bucketname: my-bucket
      cors: true
      requestParameters:
        integration.request.header.Content-Type: method.request.header.Content-Type
        integration.request.path.folder: method.request.path.userid
        integration.request.path.key: method.request.path.filename

```
It would be nice to have because if the resource already exists as a part of another CF it's quite hard to reference it
