### ISSUE TITLE
Missing Authentication Token - 403 Forbidden

### ISSUE THREAD

**Issue by serverlesspolska** [serverless-operations/serverless-apigateway-service-proxy#110]
I have defined endpoint in the following way:

```
custom:
  apiGatewayServiceProxies:
    - dynamodb:
        path: /getPartner/{PK}/{SK}
        method: GET
        tableName: { Ref: DynamoDbTable }
        authorizationType: 'NONE'
        hashKey:
          pathParam: PK
          attributeType: S
        rangeKey:
          pathParam: SK
          attributeType: S
        action: GetItem
        cors: false
```

When I am testing it inside of API Gateway console it works. Unfortunately, it doesn't work from the internet. I get the following response:
```
HTTP/1.1 403 Forbidden
Date: Mon, 09 Nov 2020 21:23:00 GMT
Content-Type: application/json
Content-Length: 42
Connection: close
x-amzn-RequestId: 1ee18fc5-78aa-4bcf-bb42-52977beb94e4
x-amzn-ErrorType: MissingAuthenticationTokenException
x-amz-apigw-id: VwjwNFuUIAMFrRA=

{
  "message": "Missing Authentication Token"
}
```

What should I do?
