### ISSUE TITLE
Error when existing apigateway resourceId is specified

### ISSUE THREAD

**Issue by devsatishm** [serverless-operations/serverless-apigateway-service-proxy#111]
Hello,

Will this plugin work with existing api gateway resources? I've tried adding one (example below) and `serverless deploy` fails with error: `The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource ApiGatewayRestApi`

```
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  apiGateway: 
    restApiId: abc123
custom:
  stage: ${opt:stage, self:provider.stage}
  feedbackTableName: jazz-user-feedback-${self:custom.stage}
  apiGatewayServiceProxies:
    - dynamodb:
        path: /feedback/{id}/{createdTs}
        method: put
        tableName: { Ref: 'FeedbackTable' }
        hashKey: # set pathParam or queryStringParam as a partitionkey.
          pathParam: id
          attributeType: S
        rangeKey: # required if also using sort key. set pathParam or queryStringParam.
          pathParam: createdTs
          attributeType: S
        action: PutItem # specify action to the table what you want
        condition: attribute_not_exists(Id) # optional Condition Expressions parameter for the table
        cors: true
```
When I don't specify `apiGateway.restApiId` property, it works as expected (creates a new apigateway resource which is not desired in our usecase). 

Any thoughts on this?

Thanks!
