### ISSUE TITLE
No Log Group For Endpoints Being Generated

### ISSUE THREAD

**Issue by isupremedyou** [serverless-operations/serverless-apigateway-service-proxy#112]
When I am using this plugin I don't seem to get any log groups created for my API Gateway during `sls deploy`.

Can anyone help explain what we may be doing wrong? Here is a sample of our serverless.yml file:
```
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2
  endpointType: REGIONAL
  logRetentionInDays: 30
  logs:
    restApi:
      level: INFO
  memorySize: 256
  timeout: 60

plugins:
  - serverless-apigateway-service-proxy

functions:
  foo:
    handler: foo.handler
    events:
      - sqs:
          arn: { "Fn::GetAtt": ["FooQueue", "Arn"] }
          batchSize: 10

resources:
  Resources:
    FooDeadLetterQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        FifoQueue: true
        QueueName: FooQueue-${self:custom.stage}.fifo
        MessageRetentionPeriod: 1209600
    FooQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        FifoQueue: true
        VisibilityTimeout: 60
        QueueName: FooQueue-${self:custom.stage}.fifo
        MessageRetentionPeriod: 1209600
        RedrivePolicy:
          deadLetterTargetArn:
            { "Fn::GetAtt": ["FooDeadLetterQueue", "Arn"] }
          maxReceiveCount: 3

custom:
  stage: ${opt:stage, self:provider.stage}
  apiGatewayServiceProxies:
    - sqs:
        path: /foo-callback/{type}/{account}/{id}/{user}
        method: post
        queueName: { "Fn::GetAtt": ["FooQueue", "QueueName"] }
        request:
          template:
            application/x-www-form-urlencoded: ${file(../vtlMappingTemplates/x-www-form-urlencoded.vtl)}
```
