### ISSUE TITLE
Ref a bucket created by serverless-finch

### ISSUE THREAD

**Issue by bayoumymac** [serverless-operations/serverless-apigateway-service-proxy#117]
Hello,

I am having trouble referencing a bucket created by `serverless-finch`, below is the `custom` section of my `serverless.yml` and the error I am getting.

```yaml
custom:
  client:
    bucketName: serverless-client
    distributionFolder: client
  apiGatewayServiceProxies:
    - s3:
        path: /
        method: get
        action: GetObject
        pathOverride: 'index.html'
        bucket:
          Ref: serverless-client
        key:
          pathParam: myKey
        cors: true
```
I run `serverless client deploy`
then I get the Error below after running `serverless deploy`
```
  Error: The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource serverless-client
      at /Users/Test/Documents/instagram-bot/serverless/node_modules/serverless/lib/plugins/aws/deploy/lib/validateTemplate.js:20:13
      at tryCatcher (/Users/Test/Documents/instagram-bot/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/Test/Documents/instagram-bot/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/Test/Documents/instagram-bot/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/Users/Test/Documents/instagram-bot/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/Users/Test/Documents/instagram-bot/serverless/node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (/Users/Test/Documents/instagram-bot/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/Users/Test/Documents/instagram-bot/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/Test/Documents/instagram-bot/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/Test/Documents/instagram-bot/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (node:internal/timers:463:21)
```
