### ISSUE TITLE
X-AMZ-ACL Header is getting created in API Gateway for the Put or Post Request.

### ISSUE THREAD

**Issue by soumyajit-convosight** [serverless-operations/serverless-apigateway-service-proxy#124]
How to remove the creation of that header in integration request. It is failing the put request with Access Denied in Open API

**Comment by arosnord** [comment]
I have the same issue. @soumyajit-convosight did you solved this problem somehow?

**Comment by arosnord** [comment]
I have found how to solve this 

```yml
custom:
  apiGatewayServiceProxies:
    - s3:
        path: /s3
        method: post
        action: PutObject
        bucket:
          Ref: S3Bucket
        cors: true

        requestParameters:
          'integration.request.path.object': 'context.requestId'
          'integration.request.header.x-amz-acl': "'private'"
```
