### ISSUE TITLE
How to connect to private s3 bucket

### ISSUE THREAD

**Issue by mengyan9521** [serverless-operations/serverless-apigateway-service-proxy#138]
I have a private s3 bucket, and I want to connect apigateway proxy with the s3 bucket.
I have set the serverless.yaml as below
```yaml
service: apigateway-upload

# frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  environment:
    S3_BUCKET_NAME: 's3-bucket-name'
  iam:
    role:
      statements:
        - Effect: 'Allow'   
          Action:
            - 's3:*'
          Resource:
            - 'arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}'
            - 'arn:aws:s3:::${self:provider.environment.S3_BUCKET_NAME}/*'

plugins:
  - serverless-apigateway-service-proxy

custom:
  apiGatewayServiceProxies:
    - s3:
        path: /s3
        method: put
        action: PutObject
        bucket: ${self:provider.environment.S3_BUCKET_NAME}
        key: static-key.json 
        cors: true
```
But when I run curl command to try to put object to the s3 bucket, I get the error message:
```
curl -X PUT https://apigatway_url_generated_from_aws/dev/s3 -d '{"message": "testtest"}' -H 'Content-Type:application/json' 
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>41BAYM9GG4VV3FEB</RequestId><HostId>+5J/7U0zjkKDHBTwm/MvqzULZ+RLn9rvcxlE4jYoungqEjD/TXGgLbrXBbUsSe7tbAJ5gObhE+VMFomXBc5byQ==</HostId></Error>%
```

I have check my iam setting, but I can not find any problem here. so what is the problem with my setting?

Can anybody help me with this issue?
