### ISSUE TITLE
Over-sized return from S3

### ISSUE THREAD

**Issue by jfederer** [serverless-operations/serverless-apigateway-service-proxy#149]
With a deployment setup like this:

```
apiGatewayServiceProxies:
  - s3:
      path: /s3/{myKey} # use path param 
      method: get
      action: GetObject
      bucket: xxxxxxx-images
      key:
        pathParam: myKey
      cors: true
      roleArn: arn:aws:iam::xxxxxxxx:role/xxxxxxIamRoleCustomResourcesAPIGateway-xxxxxx
```

And an API call like this:  https://r5po1lctjd.execute-api.us-east-1.amazonaws.com/dev/s3/xxxxxxx%2Fxxxxxxx%2Fxxxxxxx.jpg   (note, the %2F is the uri-encoded forward slash)... I expect a 133kb jpg image back.  When I call the publicly-accessible object URL of the image, I get the 133kb file with no problems.

When I use the above proxy I get a 228kb octet stream back.  

I'm at a complete loss as to why this is.  Is this configured incorrectly?

I have tried to use a queryStringParam instead with the same results.
