### ISSUE TITLE
Support for request mapping template for EventBridge

### ISSUE THREAD

**Issue by MyaElla** [serverless-operations/serverless-apigateway-service-proxy#156]
### Does the plugin support custom request mapping templates for EventBridge ? 
According to the tests in _compileMethodsToEventBridge.test.js_ , this should be functional, but I keep getting an error:

Sample serverless.yml:
```
        authorizationType: NONE
        request:
          template:
            application/json: |-
              Action=SendMessage&MessageBody=$input.body('$')
```

ISSUE : If I add a custom request template to serverless.yml I got the below error
ERROR : "child "eventbridge" fails because ["request" is not allowed]"

Noticed the docs mention a lot of customisation for other AWS services, but very limited on EB.

- [ ] (  &  'passthroughBehavior' also not allowed ?)
