### ISSUE TITLE
Kinesis selectionPattern wrong, causing deployment failure

### ISSUE THREAD

**Issue by quitedensepoint** [serverless-operations/serverless-apigateway-service-proxy#205]
The `selectionPattern` used in the code for specifically the Kinesis response templates appears to be using an incorrect number type when it should be a string. It is not overridable in the serverless.yml file. To get my team unblocked here, I had to fork this package internally with a fix.

To reproduce the problem, just attempt to deploy any Kinesis -> Lambda integration with serverless.yml code such as the following:
```
custom:
  apiGatewayServiceProxies:
    - kinesis:
        path: /myPath
        method: post
        action: PutRecord
        streamName: { Ref: 'MyStream' }
```

For full disclosure, I was deploying only to LocalStack 2.2 at the time instead of real AWS, so it's possible LocalStack is more strict than AWS here. But the AWS documentation definitely states that the expected type is a string:
[Docs Link](https://docs.aws.amazon.com/pt_br/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-method-integration-integrationresponse.html#cfn-apigateway-method-integration-integrationresponse-selectionpattern)
