### ISSUE TITLE
Allow custom response templates

### ISSUE THREAD

**Issue by rschick** [serverless-operations/serverless-apigateway-service-proxy#53]
Add the ability to use a custom response template in the `IntegrationResponse`. This is useful in the case where we don't want to reveal the internal implementation details of the proxy.

Eg.

```yml
- kinesis:
    path: /path
    method: post
    streamName: my-stream
    response:
      template:
        application/json: "{}"
```
