### ISSUE TITLE
Is SQS 'RequestTemplates' not supported by this plugin?

### ISSUE THREAD

**Issue by iDVB** [serverless-operations/serverless-apigateway-service-proxy#66]
I seems like APIG supports it but not the plugin.
```yaml
        PassthroughBehavior: NEVER
        RequestTemplates:
          application/json: |
            Action=SendMessage&MessageBody=$input.body
```
