### ISSUE TITLE
Support AWS Lambda Custom Authorizer

### ISSUE THREAD

**Issue by samuelAle** [serverless-operations/serverless-apigateway-service-proxy#72]
There is a circular dependency.

The AWS::ApiGateway::Authorizer requires a RestApiId field.

The apiGatewayServiceProxies which defines the RestApi requires the AuthorizerId.

**Comment by sagar-jani** [comment]
so, what is expected here - the apiGatewayServiceProxies has Path which is RestApiId and authorizerId ?

**Comment by felipegenef** [comment]
I'm also trying to do this! But I'm always getting the error : 
`The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [jwtAuthorizer] in the Resources block of the template`
My code:
```yaml
service: example
frameworkVersion: "3"

provider:
  name: aws
plugins:
  - serverless-apigateway-service-proxy

functions:
  jwtAuthorizer: # Custom Lambda Authorizer for SQS endpoint
    runtime: nodejs20.x
    handler: ./authorizer/index.handler

  sqsListener: # Lambda Listner for SQS endpoint
    runtime: nodejs20.x
    handler: ./SQS/index.handler
    events:
      - sqs:
          arn: !GetAtt SQSQueue.Arn

custom:
  apiGatewayServiceProxies:
    - sqs:
        path: /js/sqs
        method: post
        queueName: !GetAtt SQSQueue.QueueName
        cors: true
        authorizationType: "CUSTOM"
        authorizerId: !Ref jwtAuthorizer
        response:
          template:
            success: |
              {
                "success": "success sending to SQS"
              }
            serverError: |
              {
                "success": false,
                "errorMessage": "Server Error"
              }
            clientError: |
              {
                "success": false,
                "errorMessage": "Client Error"
              }

resources:
  Resources:
    SQSQueue:
      Type: "AWS::SQS::Queue"

```

**Comment by felipegenef** [comment]
I've done it ! @samuelAle @sagar-jani 
You just need to create another function as an authorizer, add it to any endpoint of your api and add `{ "Ref": JwtAuthorizerApiGatewayAuthorizer }`  to the `authorizerId` .
What happens under the hood is that serverless framework will create all resources needed for the lambda function authorizer. Then you just need to reference it as `"yourAuthorizerName" + "ApiGatewayAuthorizer"`, in my case `"JwtAuthorizer" + "ApiGatewayAuthorizer"`.
Anyway, that is a workaround. it would be nice to have it natively.

```yaml
service: example
frameworkVersion: "3"

provider:
  name: aws
  runtime: custom

plugins:
  - serverless-apigateway-service-proxy

functions:
  jwtAuthorizer: # Custom Lambda Authorizer for SQS endpoint
    runtime: nodejs20.x
    handler: ./authorizer/index.handler

  sqsListener: # Lambda Listner for SQS endpoint
    runtime: nodejs20.x
    handler: ./SQS/index.handler
    events:
      - sqs:
          arn: !GetAtt SQSQueue.Arn

  jsIsolatedFunction: # Use specific routes to override your Micro-service when you need a custom Memory/ CPU env for one endpoint only
    runtime: nodejs20.x
    memorySize: 512
    handler: ./IsolatedJS/index.handler
    events:
      - http:
          path: /js/api/isolated
          method: GET
          authorizer: jwtAuthorizer


custom:
  apiGatewayServiceProxies:
    - sqs:
        path: /js/sqs
        method: post
        queueName: !GetAtt SQSQueue.QueueName
        cors: true
        authorizationType: "CUSTOM"
        authorizerId: { "Ref": JwtAuthorizerApiGatewayAuthorizer }
        response:
          template:
            success: |
              {
                "success": "success sending to SQS"
              }
            serverError: |
              {
                "success": false,
                "errorMessage": "Server Error"
              }
            clientError: |
              {
                "success": false,
                "errorMessage": "Client Error"
              }

resources:
  Resources:
    SQSQueue:
      Type: "AWS::SQS::Queue"

```
