### ISSUE TITLE
Fn::Sub request parameters error

### ISSUE THREAD

**Issue by miqueloi** [serverless-operations/serverless-apigateway-service-proxy#78]
I have a problem because this serverless.yml 
```
custom:
  apiGatewayServiceProxies:
    - s3:
        path: /some-path
        method: get
        action: GetObject
        bucket:
          Ref: S3StaticWebsite
        key: private/some.json
        cors:
          origins:
            - https://${self:provider.domain}
            - http://localhost
          headers:
            - Content-Type
          allowCredentials: false
```
produces this request parameters. Notice the extra single-quotes around `${bucket}`
```

"RequestParameters": {
    "integration.request.path.bucket": {
       "Fn::Sub": [
          "'${bucket}'",
                {
                  "bucket": {
                    "Ref": "S3StaticWebsite"
                }
          }
    ]
},
```

Please help
