### ISSUE TITLE
Customizing request body mapping templates for S3

### ISSUE THREAD

**Issue by horike37** [serverless-operations/serverless-apigateway-service-proxy#81]

**Comment by pseudo-su** [comment]
Would adding `response` to the s3 options also enable support for setting response headers using:

```
integration.response.header.cache-control
```

**Comment by M-Matin-dev** [comment]
Yes, you can set response headers like Cache-Control by using VTL (Velocity Template Language) in the response section of your `serverless.yml`. Here's how I managed to do it:

```
  response:
    template:
      # `success` is used when the integration response is 200
      success: |
        #set($context.responseOverride.header.Cache-Control = 'public, max-age=31536000, immutable')
        $input.body
      # `clientError` is used when the integration response is 400
      clientError: |
        #if($input.json('$').toString().contains("AccessDenied"))
          #set($context.responseOverride.status = 200)
          #set($context.responseOverride.header.Cache-Control = 'public, max-age=3600')
          {}
        #else
          { "message": $input.json('$').toString() }
        #end
      # `clientError` is used when the integration response is 500
      serverError: |
        { "message": $input.json('$').toString() }
```
