### ISSUE TITLE
ServerlessError: child "s3" fails because ["s3" must be an object]

### ISSUE THREAD

**Issue by corydorning53** [serverless-operations/serverless-apigateway-service-proxy#91]
Trying to setup an s3 proxy and getting the error when trying to `sls deploy`:
`ServerlessError: child "s3" fails because ["s3" must be an object]`

My custom config is as follows:
```
custom:
  apiGatewayServiceProxies:
    - s3:
      path: /artifact
      method: put
      action: PutObject
      bucket:
        Ref: my-artifacts
```

**Comment by corydorning53** [comment]
Realized i had a syntax error. Needed to indent the properties under 's3':
```
custom:
  apiGatewayServiceProxies:
    - s3:
        path: /artifact
        method: put
        action: PutObject
        bucket:
          Ref: my-artifacts
```
