### ISSUE TITLE
Template error: instance of Fn::GetAtt references undefined resource myBucket

### ISSUE THREAD

**Issue by corydorning53** [serverless-operations/serverless-apigateway-service-proxy#92]
I'm getting the following error when using this plugin for S3:
`Error: The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource myBucket`

My config looks like this:
```
...
functions:
  artifact:
    handler: api/artifact.artifact
    events:
      - s3:
          bucket: myBucket
          event: s3:ObjectCreated:*

custom:
  apiGatewayServiceProxies:
    - s3:
        path: /artifact/{file}
        method: put
        action: PutObject
        bucket:
          Ref: myBucket
        key:
          pathParam: file
```

**Comment by corydorning53** [comment]
i assumed incorrectly that the serverless 'artifact' function would handle the creation of `myBucket` but i still needed to specify it as a resource. adding the following resolved the issue:

```
resources:
  Resources:
    myBucket:
      Type: 'AWS::S3::Bucket'
```
